### ISSUE TITLE
Problem when I change the model to VGG, Resnet or Alexnet 

### ISSUE THREAD

**Issue by FarnooshGhadiri** [pangwong/pytorch-multi-label-classifier#2]
When I change the model to the anythings other that Light.., it gives me an error in line 30 of model.py (missed match the input)
size mismatch, m1: [1 x 8192], m2: [25088 x 4096] at /pytorch/aten/src/TH/generic/THTensorMath.c:2033

**Comment by pangwong** [comment]
You may also need to change the load_size and input_size respectively after you changed the model type, . Vgg and Resnet are designed for Imagenet and their input_size is 224 rather than 128, which is a too small input_size for their network deepth.
