### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ArchithaKrishna** [pangwong/pytorch-multi-label-classifier#4]
Unable to run the code, please help.
FileNotFoundError: [Errno 2] No such file or directory: '/data/image_server/images/CelebA/data/Align/003450.jpg'

https://drive.google.com/drive/folders/0B7EVK8r0v71pTUZsaXdaSnZBZzg is this the right dataset?

**Comment by pangwong** [comment]
You are right, you have to download CelebA dataset yourself and run with your local image path.
